###########################		LD proning	#################################
library('SNPRelate')
setwd('/home/ulg/genan/mahmoud/Annalys/Final_Analysis/Outputs/')
snpgdsBED2GDS('clean-inds-GWA-data.bed', 'clean-inds-GWA-data.fam','clean-inds-GWA-data.bim', "Data_v2.gds")
genofile <- openfn.gds("Data_v2.gds")
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"autosome.end",29)
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"X",30)
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"Y",31)
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"XY",32)
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"MT",33)
put.attr.gdsn(index.gdsn(genofile,"snp.chromosome"),"M",33)
set.seed(10000)
snpset=snpgdsLDpruning(genofile,ld.threshold=0.2)
snpset.id = unlist(snpset)
#ibd=snpgdsIBDMoM(genofile,snp.id=snpset.id)
ibd=snpgdsIBDMLE(genofile,snp.id=snpset.id, verbose=T)
ibd.coeff=snpgdsIBDSelection(ibd)
head(ibd.coeff)
write.table(ibd.coeff,file='IBD_Matrix_SNPRelate_MLE.txt',quote=F)
